language: rust
rust:
  - 1.46.0
node_js:
  - "12"
rust:
  - stable
dist: xenial
services:
  - xvfb
before_install:
  - cargo install wasm-pack --version 0.9.1
  - npm run preinstall
install: npm ci
script: npm test